import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import CustomSessionProvider from "@/providers/CustomSessionProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface IProps {
  children: React.ReactNode
}

const RootLayout: React.FC<IProps> = async ({ children }: IProps) => {
  return (
    <html lang="en">
      <CustomSessionProvider>
        <body className={inter.className}>{children}</body>
      </CustomSessionProvider>
    </html>
  )
}

export default RootLayout
